### ISSUE TITLE
Ghost changes in commits

### ISSUE THREAD

**Issue by machiav3lli** [Murmele/Gittyup#106] opened 2022-02-26 07:38 UTC
In the last I noticed that sometimes GittyUp add changes out of nothing to the staged commits, I wasn't able even to see them in the staged block. Here's the three latest examples:
- Droid-ify: [Problematic commit](https://github.com/Iamlooker/Droid-ify/commit/ce76bde6731627a29ea0dc998bd52751f75174f8) [its fix](https://github.com/Iamlooker/Droid-ify/commit/cd15f0ef707779f9e3583020f0012e0ffb4a7819)
- OABX: [Problematic commit](https://github.com/machiav3lli/oandbackupx/commit/cfdaab4dfc8da8b8342992f329e8a6a43f8bfc6b) [its fix](https://github.com/machiav3lli/oandbackupx/commit/e7a0b38a8ad7305d7ebb4422a6ff508d143071bf)
- OABX: [Problematic commit](https://github.com/machiav3lli/oandbackupx/commit/1b0e0962ec45a0a18488bdd900c577fcf6fdc779) [its fix](https://github.com/machiav3lli/oandbackupx/commit/2b9765bcd82685e8228960a3cb92d88e37e55dff)

It's also good to mention that I wasn't able to reproduce it intentionally…

**Comment by stefanknotzer** [comment] 2022-03-01 17:48
Assuming 'its fix' is the correction to the staging failure: in every case lines were erroneous deleted? So you had to add the deletions to fix the staging problem?

**Comment by machiav3lli** [comment] 2022-03-04 08:00
AUR's gittyup-git: https://aur.archlinux.org/packages/gittyup-git

**Comment by Murmele** [comment] 2022-03-05 17:55
I think I have seen this too.

**Comment by Murmele** [comment] 2022-03-10 07:10
In this scenario, `add_subdirectory(Spice)` does not show if it is staged or not. When opening a different git tool it shows that this line is staged. Maybe it is related to this bug here.
![image](https://user-images.githubusercontent.com/10099533/157607820-5662352b-f3af-409c-8563-e2dd8c29dde5.png)

**Comment by Murmele** [comment] 2022-03-15 20:58
> In this scenario, `add_subdirectory(Spice)` does not show if it is staged or not. When opening a different git tool it shows that this line is staged. Maybe it is related to this bug here. ![image](https://user-images.githubusercontent.com/10099533/157607820-5662352b-f3af-409c-8563-e2dd8c29dde5.png)

Hmm not reproducable anymore

**Comment by machiav3lli** [comment] 2022-03-17 02:36
Since my last writing, I had it only once, and still not reproducable. Maybe there's something changed partly fixing it or it's just me being more cautious with each staging and commit.

**Comment by Martin2278** [comment] 2022-03-17 09:53
No in this area nothing changed so the issue is still there

**Comment by Martin2278** [comment] 2022-03-17 09:57
I think it is a missmatch between between staged and unstaged file passed to the Filewidget.

**Comment by Murmele** [comment] 2022-04-01 10:01
Seems to be different on windows and on linux. I was able to reproduce it on windows, but on linus the behavior is different

**Comment by Murmele** [comment] 2022-04-01 16:50
I have now a reproducable example. Hope i can fix it soon

**Comment by machiav3lli** [comment] 2022-04-01 18:11
Ah, nice!

**Comment by Murmele** [comment] 2022-04-02 11:17
@machiav3lli 
Can you try if you are able to reproduce with the build artifacts from here: https://github.com/Murmele/Gittyup/pull/122

**Comment by Murmele** [comment] 2022-04-20 13:14
I close it for now. If it happens again, please reopen it

**Comment by machiav3lli** [comment] 2022-04-26 23:59
Hm.. it worked just fine till yesterday, when I had it again and till now am unable to reproduce it (Nothing changed, I'm still using the latest dev AUR gittyup-git).

**Comment by Murmele** [comment] 2022-05-22 08:18
@machiav3lli I think now I found it :) Can you have a look on the pullrequest and the description there. Maybe you remember if you had a scenario like this.
https://github.com/Murmele/Gittyup/pull/172

Please open this issue again if this does not fix you problem

**Closed by Murmele** 2022-05-22 08:18 UTC
Labels: bug

**Comment by machiav3lli** [comment] 2022-05-23 09:12
Thanks, I'll do. And please consider refreshing the AUR releases (either update the non-dev gittyup-git or do a formal release)

**Comment by Murmele** [comment] 2022-05-23 09:14
I am planning to create a new release next days. Currently we don't support officially AUR releases.

There is a discussion ongoing: https://github.com/Murmele/Gittyup/issues/167
