### ISSUE TITLE
[Feature request] [UX] Automatically refresh on focus

### ISSUE THREAD

**Issue by KaKi87** [Murmele/Gittyup#505] opened 2023-04-02 03:01 UTC
Hello,

It would be nice of Gittyup to automatically refresh status when the window is put in foreground after being in background.

Use case :
1. The user opens Gittyup, it is in foreground, status is updated ;
2. The user opens an editor and edits a file, Gittyup is in background, status is outdated ;
3. The user goes back to Gittyup, it is in foreground, status would be updated.

Thanks

**Comment by Murmele** [comment] 2023-04-02 09:05
Seems to be a bug, because Gittyup automatically refreshes whenever a file was modified

**Comment by KaKi87** [comment] 2023-04-03 03:32
After further testing, it turns out that yes, Gittyup does refresh files, but not the git status, not like when pressing the refresh button.

**Comment by Murmele** [comment] 2023-04-03 14:56
> 

Yes this is true, this data is written in the .git folder and currently we don't track this folder.

**Comment by Murmele** [comment] 2023-04-03 14:58
duplicate of #216

**Closed by Murmele** 2023-04-03 14:58 UTC

**Comment by redactedscribe** [comment] 2023-11-05 00:08
I'd also like to see the git status refresh automatically. If you stage something in VS Code, you must first press Refresh in Gittyup to update the status.
