### ISSUE TITLE
Stage all, and unstage all buttons do not work as expected

### ISSUE THREAD

**Issue by MarcelInTO** [Murmele/Gittyup#549] opened 2023-05-14 14:04 UTC
I have a set of unstaged files that are all two or three directories deep. They are all show correctly, expanded, in the "unstaged section". None are checked.

Selecting the checkbox on the files in the unstaged section moves them to the staged section, as expected.

However selecting the "stage all" or "unstage all" buttons does not work as expected.

If I hit "stage all", all the files disappear from the unstaged section, but do not appear in the staged section. Furthermore, the directorty names remain in the unstaged section but are now checked.  Nothing appears in the staged section at all,

The analogous behavior happens with the unstage all button.

I have a tree of files in the staged files selction. None are selected. I hit the unstage all button and all the filenames disappear, the directory names stay, nothing is checked any more, but nothing appears in the usntaged section.

Attaching screenshot that shows a tree of files, and a second screenshot that shows the results after hitting "stage all".

![image](https://github.com/Murmele/Gittyup/assets/5455478/b79b5e38-cad6-4212-be95-fe520d3d5c26)

![image](https://github.com/Murmele/Gittyup/assets/5455478/598bda44-88b8-4957-a467-642b04b893ad)

**Comment by Murmele** [comment] 2023-05-16 15:42
duplicate of #244 Can you try with the latest development release?

**Closed** 2023-05-16 15:47 UTC

**Comment by MarcelInTO** [comment] 2023-05-17 15:26
I tested with the latest development release and it does fix my use case. Sorry for the duplicate; I had searched to see if it had already been reported before I filed the bug, but it did not occur to me search closed issues.

**Comment by Murmele** [comment] 2023-05-17 20:56
@MarcelInTO it is not a problem creating a duplicate. Thank you for the confirmation!
