### ISSUE TITLE
Question or bug? I can't find any button to expand right pane of the committed files

### ISSUE THREAD

**Issue by dekomorii** [Murmele/Gittyup#307] opened 2022-10-12 15:17 UTC
I closed the right pane accidentally where committed files are located and I've been trying to find a button that expands it like how the repo sidebar is expand with a button

**Comment by exactly-one-kas** [comment] 2022-10-13 10:07
You can "resize" it back, there's a 2 pixel wide area at the right border of the window where your cursor should indicate that you can resize the area. You can maximize the window on the rightmost screen to have an easier time doing that

**Comment by exactly-one-kas** [comment] 2022-10-13 10:08
Closing as a duplicate of #269

**Closed by exactly-one-kas** 2022-10-13 10:08 UTC
Labels: duplicate
