### ISSUE TITLE
arch aur build broken

### ISSUE THREAD

**Issue by ftaiolivista** [Murmele/Gittyup#259] opened 2022-08-31 08:32 UTC
The build have success but launching give

Theme dir:  QDir( "/home/vista/.cache/yay/gittyup/src/build/Resources" , nameFilters = { "*" },  QDir::SortFlags( Name | IgnoreCase ) , QDir::Filters( Dirs|Files|Drives|AllEntries ) )
Theme dir:  QDir( "/home/vista/.cache/yay/gittyup/src/build/Resources" , nameFilters = { "*" },  QDir::SortFlags( Name | IgnoreCase ) , QDir::Filters( Dirs|Files|Drives|AllEntries ) )
PANIC: unprotected error in call to Lua API (cannot open /home/user/.cache/yay/gittyup/src/build/Resources/System.lua: No such file or directory)
[1]    305022 IOT instruction (core dumped)  **gittyup**

[Please see comments on AUR page](https://aur.archlinux.org/packages/gittyup)

**Comment by alerque** [comment] 2022-08-31 08:44
I'm the author of the AUR package, but the real problem is upstream and already know. In fact the author was working on a fix, but it hasn't gotten merged yet.

See #191.

**Comment by exactly-one-kas** [comment] 2022-08-31 19:50
Closing as duplicate of #217

**Closed by exactly-one-kas** 2022-08-31 19:50 UTC
Labels: bug, duplicate, linux
