### ISSUE TITLE
Menu bar not showing in global menu

### ISSUE THREAD

**Issue by qingxiang-jia** [Murmele/Gittyup#205] opened 2022-06-23 13:18 UTC
When using KDE with global menu enabled, the app no longer has its menu bar displayed in app (this is probably okay), but the menu bar also doesn't show up in global menu (this is problematic).

I think we could either don't support global menu at all, just show a menu bar no matter what. Or, we support global menu. BTW, the usual workaround of having application menu in title bar also doesn't work. So, effectively, I don't have access to most of the settings.

This happens with both the AUR version and flatpak version.

OS: ArchLinux
KDE: 5.25.1
KDE Plasma Version: 5.95.0
Qt Version: 5.15.5
Kernel Version: 5.18.5-arch1-1
Graphics Platform: X11

![image](https://user-images.githubusercontent.com/5571586/175308251-78666b5e-0e67-46fc-852d-c0c9aeca11e7.png)

**Comment by Murmele** [comment] 2022-06-30 11:39
duplicate of #36

**Closed by Murmele** 2022-06-30 11:39 UTC
