### ISSUE TITLE
"External Diff" not working

### ISSUE THREAD

**Issue by systemoperator** [Murmele/Gittyup#481] opened 2023-03-03 01:55 UTC
Seems to be a duplicate for #438.

Selecting two commits, right-clicking on a file in the list of committed files and choosing `External Diff` does not work.

Observation: Nothing happens at all (no error, no window). I've tried it with different diff tools (`k3diff`, `meld`, ...). I want to use `meld`.

The application only logs the following in terminal:

```
Root dir:  QDir( "/app/bin" , nameFilters = { "*" },  QDir::SortFlags( Name | IgnoreCase ) , QDir::Filters( Dirs|Files|Drives|AllEntries ) )
Conf dir:  QDir( "/app/share/gittyup/Resources" , nameFilters = { "*" },  QDir::SortFlags( Name | IgnoreCase ) , QDir::Filters( Dirs|Files|Drives|AllEntries ) )
```

Operating system: Debian 11, Mate Desktop 1.24.1 with Marco window manager
Running the latest version of Gittyup (v1.2.2), using flatpak

Contrarily, with the latest version of **GitAhead**, the `External Diff` command works flawlessly (e.g. with `meld`). The `meld` window pops up. I've compared all the settings in GitAhead with Gittyup, they all are the same. The only difference, I can see now, is that Gittyup is run with root privileges and GitAhead not. Maybe this references a wrong path? In the settings, both applications open the config file of the same user, residing in `~/.gitconfig`, so this looks fine.

Add: Ok, running with root privileges seems to be a bug with mate desktop running Marco window manager with flatpak, where MATE's window manager Marco is misreporting that Flatpak applications are running as root when they aren't:
- https://www.linuxquestions.org/questions/linux-software-2/why-do-flatpak-programs-have-as-superuser-in-the-title-bar-4175645382/
- https://github.com/mate-desktop/marco/issues/301

**Comment by Murmele** [comment] 2023-03-03 20:06
duplicate of https://github.com/Murmele/Gittyup/issues/482

**Closed by Murmele** 2023-03-03 20:06 UTC
