### ISSUE TITLE
Crashes when merging changes

### ISSUE THREAD

**Issue by 0verEngineer** [Murmele/Gittyup#365] opened 2022-11-15 09:29 UTC
I use the Flatpak with version v1.2.0.
Lately i discovered crashes everytime i try to merge the remote master into my local branch when i am using the `Use Ours / Use Theirs` Buttons and then after pressing the `Save` Button it crashes.

Here is the log that is being printed after pressing the `Save` Button:

```Root dir:  QDir( "/app/bin" , nameFilters = { "*" },  QDir::SortFlags( Name | IgnoreCase ) , QDir::Filters( Dirs|Files|Drives|AllEntries ) )
Conf dir:  QDir( "/app/share/gittyup/Resources" , nameFilters = { "*" },  QDir::SortFlags( Name | IgnoreCase ) , QDir::Filters( Dirs|Files|Drives|AllEntries ) )
Lexers dir:  QDir( "/app/share/gittyup/Resources/lexers" , nameFilters = { "*" },  QDir::SortFlags( Name | IgnoreCase ) , QDir::Filters( Dirs|Files|Drives|AllEntries ) )
ReferenceView: Local branches:  "DTDP-398"
...
ReferenceView: Remote branches:  "origin/revert-74e4c4b6"
Root dir:  QDir( "/app/bin" , nameFilters = { "*" },  QDir::SortFlags( Name | IgnoreCase ) , QDir::Filters( Dirs|Files|Drives|AllEntries ) )
Conf dir:  QDir( "/app/share/gittyup/Resources" , nameFilters = { "*" },  QDir::SortFlags( Name | IgnoreCase ) , QDir::Filters( Dirs|Files|Drives|AllEntries ) )
Name:  "Unstaged" Current Collapsed:  3 ; New Collapsed:  1
Name:  "Staged" Current Collapsed:  4 ; New Collapsed:  4
Root dir:  QDir( "/app/bin" , nameFilters = { "*" },  QDir::SortFlags( Name | IgnoreCase ) , QDir::Filters( Dirs|Files|Drives|AllEntries ) )
Conf dir:  QDir( "/app/share/gittyup/Resources" , nameFilters = { "*" },  QDir::SortFlags( Name | IgnoreCase ) , QDir::Filters( Dirs|Files|Drives|AllEntries ) )
Lexers dir:  QDir( "/app/share/gittyup/Resources/lexers" , nameFilters = { "*" },  QDir::SortFlags( Name | IgnoreCase ) , QDir::Filters( Dirs|Files|Drives|AllEntries ) )
Expanded: Name:  "Unstaged" , Index data:  "concrete_services"
Name:  "Unstaged"  Row:  0 :  "StockDataProviderService.java" ; Count:  0
Name:  "Unstaged" , countCollapsed(): 0
Name:  "Unstaged" Current Collapsed:  1 ; New Collapsed:  0
Expanded: Name:  "Unstaged" , Index data:  "services"
Name:  "Unstaged"  Row:  0 :  "concrete_services" ; Count:  0
Name:  "Unstaged"  Row:  1 :  "service_configs" ; Count:  1
Name:  "Unstaged" , countCollapsed(): 1
Name:  "Unstaged" Current Collapsed:  0 ; New Collapsed:  0
Expanded: Name:  "Unstaged" , Index data:  "entities"
Name:  "Unstaged"  Row:  0 :  "services" ; Count:  0
Name:  "Unstaged" , countCollapsed(): 0
Name:  "Unstaged" Current Collapsed:  0 ; New Collapsed:  -1
Gittyup: /run/build/Gittyup/src/ui/TreeView.cpp:169: void TreeView::setCollapseCount(int): Assertion `value >= 0' failed.```

**Comment by exactly-one-kas** [comment] 2022-11-15 11:12
@Murmele I think this is the relevant part:
```
Gittyup: /run/build/Gittyup/src/ui/TreeView.cpp:169: void TreeView::setCollapseCount(int): Assertion `value >= 0' failed.
```

**Comment by Murmele** [comment] 2022-11-16 12:01
somewhere the collapse counter is not set correctly

**Comment by Murmele** [comment] 2022-11-16 12:09
Can you try to reproduce the error on a test repository. It has to do something with the filestructure. So the content is not relevant.

**Comment by 0verEngineer** [comment] 2022-11-17 22:00
I do not remember the exact context how it happened, i will setup a test repository with steps to reproduce the problem the next time i stumble over it.

**Comment by Murmele** [comment] 2022-11-18 14:33
Great thank you. Because I am not able to reproduce it

**Comment by Murmele** [comment] 2022-11-21 09:44
Can you do the test from startup and filter out all those messages:

Expanded: Name: *
Collapsed: Name: *
Name:*Current Collapsed: *

from this we might be able to reproduce the issue

**Comment by Murmele** [comment] 2022-11-21 09:50
Can you apply this patch (I had to zip it to upload) to the current master and provide the logs from above?

[0001-add-debug-message-for-merge-conflicts.zip](https://github.com/Murmele/Gittyup/files/10055314/0001-add-debug-message-for-merge-conflicts.zip)

**Comment by Murmele** [comment] 2022-11-21 09:59
Is everything collapsed at the beginning of the merge?

**Comment by Murmele** [comment] 2022-11-21 10:23
@0verEngineer Can you take a screenshot of the treeview, you can blur/remove the content. I just would like to see the folder structure before the merge will be done.
If you are debugging. You can share also a screenshot how it looks during the merge when you solve the merge conflict

**Comment by 0verEngineer** [comment] 2022-11-21 19:17
Log from the test with your branch:
```
TreeView::expandAll
Name:  "Unstaged" Current Collapsed:  0 ; New Collapsed:  0
TreeView::expandAll
Name:  "Unstaged" Current Collapsed:  0 ; New Collapsed:  0
TreeView::collapseAll:  2
Name:  "Unstaged" Current Collapsed:  0 ; New Collapsed:  2
TreeView::collapseAll:  0
Name:  "Staged" Current Collapsed:  4 ; New Collapsed:  0
TreeView::collapseAll:  2
Name:  "Unstaged" Current Collapsed:  2 ; New Collapsed:  2
TreeView::collapseAll:  4
Name:  "Staged" Current Collapsed:  0 ; New Collapsed:  4
TreeView::collapseAll:  2
Name:  "Unstaged" Current Collapsed:  2 ; New Collapsed:  2
TreeView::collapseAll:  4
Name:  "Staged" Current Collapsed:  4 ; New Collapsed:  4
TreeView::expandAll
Name:  "Unstaged" Current Collapsed:  0 ; New Collapsed:  2
TreeView::collapseAll:  4
Name:  "Staged" Current Collapsed:  4 ; New Collapsed:  4
TreeView::itemExpanded Name:  "Unstaged" Row:  0
TreeView::itemExpanded Parent  1 Row:  0
TreeView::itemExpanded Parent  2 Row:  0
TreeView::itemExpanded Parent  3 Row:  0
TreeView::itemExpanded Parent  4 Row:  0
TreeView::itemExpanded Parent  5 Row:  0
TreeView::itemExpanded Parent  6 Row:  0
TreeView::itemExpanded Parent  7 Row:  0
TreeView::itemExpanded Parent  8 Row:  0
Name:  "Unstaged"  Row:  0 :  "StandardSecurityConfiguration.java" ; Count:  0
Name:  "Unstaged" , countCollapsed(): 0
Name:  "Unstaged" Current Collapsed:  2 ; New Collapsed:  1
TreeView::itemExpanded Name:  "Unstaged" Row:  0
TreeView::itemExpanded Parent  1 Row:  0
TreeView::itemExpanded Parent  2 Row:  0
TreeView::itemExpanded Parent  3 Row:  0
TreeView::itemExpanded Parent  4 Row:  0
TreeView::itemExpanded Parent  5 Row:  0
TreeView::itemExpanded Parent  6 Row:  0
TreeView::itemExpanded Parent  7 Row:  0
Name:  "Unstaged"  Row:  0 :  "security_configs" ; Count:  0
Name:  "Unstaged" , countCollapsed(): 0
Name:  "Unstaged" Current Collapsed:  1 ; New Collapsed:  0
TreeView::itemExpanded Name:  "Unstaged" Row:  0
TreeView::itemExpanded Parent  1 Row:  0
TreeView::itemExpanded Parent  2 Row:  0
TreeView::itemExpanded Parent  3 Row:  0
TreeView::itemExpanded Parent  4 Row:  0
TreeView::itemExpanded Parent  5 Row:  0
TreeView::itemExpanded Parent  6 Row:  0
Name:  "Unstaged"  Row:  0 :  "configs" ; Count:  0
Name:  "Unstaged" , countCollapsed(): 0
Name:  "Unstaged" Current Collapsed:  0 ; New Collapsed:  -1
Gittyup: /home/xps/Projects/Gittyup/src/ui/TreeView.cpp:169: void TreeView::setCollapseCount(int): Assertion `value >= 0' failed.
```


Screenshots:
After the start of the merge (everything is collapsed):
![after_start](https://user-images.githubusercontent.com/105462605/203140374-e2507bb9-4b9d-48f9-acff-2c1b53145c0a.png)

Then i click `Expand All` and it looks like this:
![after_expand_all](https://user-images.githubusercontent.com/105462605/203140504-6ecddd93-c597-4ba3-a1fd-4f7da835e874.png)

**Comment by Murmele** [comment] 2022-11-22 17:29
I am able to reproduce:
[CrashMerge.zip](https://github.com/Murmele/Gittyup/files/10069669/CrashMerge.zip)

Steps to reproduce:
1) Open attached repository
2) Merge `otherBranch` into master
3) Click `Expand all` for unstaged Files
![image](https://user-images.githubusercontent.com/10099533/203381621-b24b1a1d-63e1-4a09-aa86-cdc661da3c28.png)

4) Select File_security_config
5) Click `Use Ours`
6) Click `Save`

**Comment by Murmele** [comment] 2022-11-22 18:37
thanks @0verEngineer I found the issue and fixed in my branch

**Comment by Murmele** [comment] 2023-01-23 14:46
@0verEngineer can you retry with version 1.2.2?

**Comment by 0verEngineer** [comment] 2023-01-23 18:37
@Murmele Yes it works.

**Closed** 2023-01-23 18:37 UTC
Labels: bug
